config/routes.rb
Rails.application.routes.draw do
  root to: 'phones#index'
    resources :phones
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/phone.rb
class Phone < ApplicationRecord
  COLORS = ['Rouge', 'Vert', 'Bleu']
  CAPACITY = [2, 4, 6, 8, 10, 12, 16, 32, 64, 128, 256, 512]
  validates :capacity, inclusion: { in: CAPACITY }
  validates :color, inclusion: { in: COLORS }
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  def index
    @phones = Phone.all
  end

  def show
    @phone = Phone.find(params[:id])
  end

  def new
    @phone = Phone.new
  end

  def create
    @phone = Phone.new(phone_params)

    if @phone.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @phone = Phone.find(params[:id])
  end

  def update
    @phone = Phone.find(params[:id])
    if @phone.update(phone_params)
      redirect_to root_path, notice: 'modifié!'
    else
      render :edit
    end
  end

  def destroy
    @phone = Phone.find(params[:id])
    @phone.destroy
    redirect_to root_path
  end

  private

  def phone_params
    params.require(:phone).permit(:name, :brand, :imei, :color, :capacity)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestMinim</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/phones/edit.html.erb
<h1>éditer le téléphone</h1>
<div class="row">
  <div class="col-sm-4 col-sm-offset-4">
    <div class="form-inputs">
      <%= simple_form_for [@phone] do |f| %>
      <%= f.input :name, label: 'Nom', required: true %>
      <%= f.input :brand, label: 'Marque' %>
      <%= f.input :color,:collection => Phone::COLORS, label: 'Couleur' %>
      <%= f.input :imei, label: 'IMEI' %>
      <%= f.input :capacity,:collection => Phone::CAPACITY, label: 'Capacité' %>

      <%= f.button :submit, "Valider", class: "btn btn-primary" %>
    </div>
  </div>
</div>
<% end %>

app/views/phones/index.html.erb
<div class="container">
  <%= link_to 'créer un téléphone', new_phone_path, class: 'btn btn-warning m-4' %>
    <% @phones.sort_by(&:created_at).reverse.each do |phone| %>
      <div class="card mb-4">
        <%= link_to phone_path(phone), class: "text-center" do %>
          <h4 class="text-center m-2">
            Nom: <%= phone.name %> <br>
            Marque: <%= phone.brand %> <br>
            Couleur: <%= phone.color %> <br>
            IMEI: <%= phone.imei %> <br>
            Capacité: <%= phone.capacity %> <br>


          </h4>
        <% end %>
        <%= link_to 'Edit', edit_phone_path(phone), class: "btn btn-warning" %>
        <%= button_to "Destroy", phone, method: :delete, data: { confirm: "Êtes-vous sur?"} %>
      </div>
    <% end %>
</div>

app/views/phones/new.html.erb
<h1>nouveau téléphone</h1>
<div class="row">
  <div class="col-sm-4 col-sm-offset-4">
    <div class="form-inputs">
      <%= simple_form_for [@phone] do |f| %>
      <%= f.input :name, label: 'Nom' %>
      <%= f.input :brand, label: 'Marque' %>
      <%= f.input :color,:collection => Phone::COLORS, label: 'Couleur' %>
      <%= f.input :imei, label: 'IMEI' %>
      <%= f.input :capacity,:collection => Phone::CAPACITY, label: 'Capacité' %>

      <%= f.button :submit, "Valider", class: "btn btn-primary" %>
    </div>
  </div>
</div>
<% end %>

app/views/phones/show.html.erb
<h2 class="text-center m-2">
  Nom:<%= @phone.name %> <br>
  Marque: <%= @phone.brand %> <br>
  Couleur: <%= @phone.color %> <br>
  IMEI: <%= @phone.imei %> <br>
  Capacité: <%= @phone.capacity %> <br>

</h2>

<%= link_to 'Edit', edit_phone_path(@phone), class: "btn btn-warning" %>

<%= link_to 'Retour', phones_path %>